version: "3.9"

services:
  cache:
    container_name: redis_cache
    image: redis:7.0.9-bullseye
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile.redis
    tty: true
    stdin_open: true
    # env_file:
    #   - ./.env
    environment:
      - REDIS_PASS=${REDIS_PASS:+correcthorsebatterystaple}
    restart: unless-stopped
    volumes:
      - ./redis.conf:/data/redis.conf
      - /tmp/redis_cache:/data
    ports:
      - 6379:6379/tcp
    command: /usr/local/bin/redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    # command: /bin/bash

networks:
  default:
    driver: bridge
