# code: language=ansible

---
- hosts: localhost
  connection: local
  become: false
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  vars:
    os_environment:
      - key: EDITOR
        value: vim
    container_name: ubuntu
    container_image: ubuntu:latest
    container_command: sleep 1d
  pre_tasks:
    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"
        work_dir: "{{ playbook_dir | dirname }}"
        cacheable: true
      tags: qa

    - name: Top-level directory in project
      ansible.builtin.shell: git rev-parse --show-toplevel
      register: tld
      tags: qa

    - name: Set tld stdout fact
      ansible.builtin.set_fact:
        tld: "{{ tld.stdout }}"
      tags: qa

    - name: Get OS release
      ansible.builtin.set_fact:
        os_release: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
        major_ver: "{{ ansible_distribution_major_version }}"
        distro: "{{ ansible_distribution }}"
      tags: qa

    - name: Cross-platform dependencies
      ansible.builtin.package:
        name:
        - acl
        - ansible
        - ansible-lint
        - bats
        - ca-certificates
        - cloud-init
        - fzf
        - git
        - inxi
        - python3.10
        - python3
        - python3-redis
        - python3-psutil
        - tree
        - vim
        state: present
      become: true
  tasks:
    - name: Enable rpmfusion repos
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: yes
      with_items:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{major_ver}}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{major_ver}}.noarch.rpm"
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install redhat dependencies
      ansible.builtin.dnf:
        name:
        - dnf-utils
        - dnf-plugins-core
        - firewall-config
        - NetworkManager-tui
        update_cache: yes
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Add extra repos
      ansible.builtin.shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/{{ distro | lower }}/docker-ce.repo
      args:
        executable: /bin/bash
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install docker
      ansible.builtin.dnf:
        name:
        - containerd.io
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        update_cache: yes
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Activate ip_tables module
      ansible.builtin.shell: |
        modprobe ip_tables
        modprobe br_netfilter
        echo ip_tables > /etc/modules-load.d/ip_tables.conf
        echo br_netfilter > /etc/modules-load.d/br_netfilter.conf
      args:
        executable: /bin/bash
      become: true
      when: ansible_os_family == "RedHat"

    - name: grubby
      become: true
      ansible.builtin.shell: |
        grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=1"
      args:
        executable: /bin/bash
      when: ansible_os_family == "RedHat"

    - name: Install docker python module
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Enable docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
      become: true

    - name: Enable containerd service
      ansible.builtin.service:
        name: containerd
        enabled: true
        state: started
      become: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ local_user }}"
        groups: docker
        append: yes
      become: true

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        command: "{{ container_command }}"
        state: present

    - name: Install distrobox
      ansible.builtin.dnf:
        name:
        - distrobox
        update_cache: yes
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Create distrobox config directory
      ansible.builtin.file:
        path: "{{ home_dir }}/.config/distrobox"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0755
      become: false
      tags: qa

    - name: distrobox config
      ansible.builtin.copy:
        src: "{{ tld }}/config/.distroboxrc"
        dest: "{{ home_dir }}/.config/distrobox/distrobox.conf"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0644
      become: false
      tags: qa
