# code: language=ansible

# SOURCE: https://gist.github.com/mkubenka/f234bc17b693c513feddcb565265212e

---
- hosts: localhost
  connection: local
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  vars:
    base_dir: "{{ home_dir }}/git/nerd-fonts"
    repo_url: https://github.com/ryanoasis/nerd-fonts.git
    version: master
    sparse_checkout: patched-fonts/Hack
  pre_tasks:
    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"
        work_dir: "{{ playbook_dir | dirname }}"
        cacheable: true
  tasks:
    - name: Create repo directory
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0755

    - name: Prepare sparse git repository
      shell: |
        git init
        git config core.sparsecheckout true
        git remote add origin {{ repo_url }}
      args:
        chdir: "{{ base_dir }}"
        creates: "{{ base_dir }}/.git"

    - name: Configure sparse-checkout
      copy:
        dest: "{{ base_dir }}/.git/info/sparse-checkout"
        content: '{{ sparse_checkout | join("\n") }}'

    - name: Clone repo
      shell: git pull origin "{{ version }}"
      args:
        chdir: "{{ base_dir }}"
        creates: "{{ base_dir }}/{{ sparse_checkout | first }}"
