# code: language=ansible

---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  collections:
    - community.general
  vars:
    os_environment:
      - key: EDITOR
        value: vim
    git_user:
      - key: user.name
        value: pythoninthegrass
      - key: user.email
        value: 4097471+pythoninthegrass@users.noreply.github.com
  pre_tasks:
    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"
        work_dir: "{{ playbook_dir | dirname }}"
        cacheable: true
      delegate_to: localhost
      tags: qa

    - name: Register ~/.gitconfig user.name and user.email
      ansible.builtin.shell: |
        git config --global user.name "{{ git_user.0.value }}"
        git config --global user.email "{{ git_user.1.value }}"
      become: false

    - name: Cross-platform dependencies
      become_user: root
      ansible.builtin.package:
        name:
        - acl
        - git
        state: present
  tasks:
    - name: Add a setting to ~/.gitconfig
      community.general.git_config:
        name: alias.amend
        scope: global
        value: commit --amend --no-edit
      become: false

    - name: Add a setting to ~/.gitconfig
      community.general.git_config:
        name: push.autoSetupRemote
        scope: global
        value: true
      become: false

    - name: Setup directory for git repos
      ansible.builtin.file:
        path: "{{ home_dir }}/git"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        # mode: 01777
        recurse: true

    - name: Clone hardening repo
      become: false
      ansible.builtin.git:
        repo: https://github.com/pythoninthegrass/hardening.git
        dest: "{{ home_dir }}/git/hardening"
        clone: true
        update: true
        force: true
        version: master

    - name: Clone ansible hardening repo
      ansible.builtin.git:
        repo: https://github.com/pythoninthegrass/ansible-role-hardening.git
        dest: /etc/ansible/roles/hardening
        clone: true
        update: true
        force: true
        version: master

    - name: Take ownership of hardening repo
      ansible.builtin.file:
        path: /etc/ansible/roles/hardening
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        # mode: 01777
        recurse: true
